name: Keep Render Services Alive

on:
  schedule:
    # Her 10 dakikada bir çalış (cron format: minute hour day month dayofweek)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Manuel tetikleme

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          echo "Pinging backend..."
          curl -f https://barcodepos-backend.onrender.com/health || echo "Backend ping failed"
          
      - name: Ping Frontend
        run: |
          echo "Pinging frontend..."
          curl -f https://www.barcodepos.trade || echo "Frontend ping failed"
          
      - name: Success
        run: echo "✅ Keepalive ping completed"

